name: Deploy to Linux VM

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.HOST_SSH_KEY }}
          passphrase: ""
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          key: ${{ secrets.HOST_SSH_KEY }}
          passphrase: ""
          script: |
            cd /home/azureuser/frontend
            git pull origin main
