name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
 test:
  runs-on: ubuntu-latest
  container:
    image: node:20
  steps:
    - uses: actions/checkout@v3
      with:
        node-version: '20'
    - name: Ensure package-lock.json exists
      run: |
        if [ ! -f package-lock.json ]; then
          npm install --package-lock-only
        fi
    - run: npm ci 
    - run: npm test
    - run: npm run build
