name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
      working-directory: bootcamp
    - name: Run tests
      run: npm test
      working-directory: bootcamp
    - name: Build React app
      run: npm run build
      working-directory: bootcamp
